version: '3.8'
services:
  app_blue:
    build:
      context: service
    environment:
      NAME: blue
    ports:
      - 3000:3000
  app_green:
    build:
      context: service
    environment:
      NAME: green
    ports:
      - 3001:3000
  app_red:
    build:
      context: service
    environment:
      NAME: red
    ports:
      - 3002:3000
  kong:
    image: kong:3.5
    environment:
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: warn
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    ports:
      - 8000:8000
      - 8001:8001
